#
# (#)libs.versions.toml 0.2.0   06/12/2026
# (#)libs.versions.toml 0.1.0   05/30/2026
#
#  @author   Jonathan Parker
#  @version  0.2.0
#  @since    0.1.0
#
#  MIT License
#
#  Copyright (c) 2026 Jonathan M. Parker
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#  
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

[versions]
ch-qos-logback-logback-classic = "1.5.32"
jakarta-platform-jakarta-jakartaee-api = "11.0.0"
jakarta-servlet-jsp-jstl-jakarta-servlet-jsp-jstl-api = "3.0.2"
jakarta-ws-rs-jakarta-ws-rs-api = "4.0.0"
net-jmp-util-logging-logging-utilities = "1.2.0"
org-glassfish-expressly-expressly = "6.0.0"
org-glassfish-jersey-core-jersey-common = "4.0.0"
org-glassfish-web-jakarta-servlet-jsp-jstl = "3.0.1"
org-hibernate-validator-hibernate-validator = "9.1.0.Final"
org-jspecify-jspecify = "1.0.0"
org-junit-jupiter-junit-jupiter = "6.1.0"
org-mockito-mockito-core = "5.23.0"
org-mockito-mockito-junit-jupiter = "5.23.0"
org-mongodb-mongodb-driver-sync = "5.8.0"
org-slf4j-slf4j-api = "2.0.18"
org-xerial-sqlite-jdbc = "3.53.2.0"

[libraries]
ch-qos-logback-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "ch-qos-logback-logback-classic" }
jakarta-platform-jakarta-jakartaee-api = { module = "jakarta.platform:jakarta.jakartaee-api", version.ref = "jakarta-platform-jakarta-jakartaee-api" }
jakarta-servlet-jsp-jstl-jakarta-servlet-jsp-jstl-api = { module = "jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api", version.ref = "jakarta-servlet-jsp-jstl-jakarta-servlet-jsp-jstl-api" }
jakarta-ws-rs-jakarta-ws-rs-api = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "jakarta-ws-rs-jakarta-ws-rs-api" }
net-jmp-util-logging-logging-utilities = { module = "net.jmp.util.logging:logging-utilities", version.ref = "net-jmp-util-logging-logging-utilities" }
org-glassfish-expressly-expressly = { module = "org.glassfish.expressly:expressly", version.ref = "org-glassfish-expressly-expressly" }
org-glassfish-jersey-core-jersey-common = { module = "org.glassfish.jersey.core:jersey-common", version.ref = "org-glassfish-jersey-core-jersey-common" }
org-glassfish-web-jakarta-servlet-jsp-jstl = { module = "org.glassfish.web:jakarta.servlet.jsp.jstl", version.ref = "org-glassfish-web-jakarta-servlet-jsp-jstl" }
org-hibernate-validator-hibernate-validator = { module = "org.hibernate.validator:hibernate-validator", version.ref = "org-hibernate-validator-hibernate-validator" }
org-jspecify-jspecify = { module = "org.jspecify:jspecify", version.ref = "org-jspecify-jspecify" }
org-junit-jupiter-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "org-junit-jupiter-junit-jupiter" }
org-mockito-mockito-core = { module = "org.mockito:mockito-core", version.ref = "org-mockito-mockito-core" }
org-mockito-mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "org-mockito-mockito-junit-jupiter" }
org-mongodb-mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "org-mongodb-mongodb-driver-sync" }
org-slf4j-slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "org-slf4j-slf4j-api" }
org-xerial-sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "org-xerial-sqlite-jdbc" }

[bundles]
jakarta = [
    "jakarta-platform-jakarta-jakartaee-api",
    "jakarta-servlet-jsp-jstl-jakarta-servlet-jsp-jstl-api",
    "jakarta-ws-rs-jakarta-ws-rs-api"
]

logging = [
    "ch-qos-logback-logback-classic",
    "net-jmp-util-logging-logging-utilities",
    "org-slf4j-slf4j-api"
]

testing = [
    "org-junit-jupiter-junit-jupiter",
    "org-mockito-mockito-junit-jupiter"
]
